[workspace]
resolver = "2"
members = [
    "basic-blink", 
    "bmp-280", "irq_test", 
    "multicore-serial",
	"test-pwm",
    "test-rom",
    "uart"
    ]

[patch.crates-io]
delog = {git = "https://github.com/LechevSpace/delog.git", rev = "869167f7ff0630518c86f30afd215fee124d19c1"}
